version: '3.4'

services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    restart: unless-stopped
    image: redis:6.2-alpine
    environment:
      REDIS_PASSWORD: "redis"
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
     - "6379:6379"

  nats:
    restart: unless-stopped
    image: nats:2.10.11-alpine
    ports:
      - 8222:8222
      - 4222:4222
    command: "--http_port 8222"
    networks: ["nats"]

  clickhouse:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: "logs"
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

networks:
  nats:
    name: nats

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:


